### ISSUE TITLE
Error for the Theme Gestion

### ISSUE THREAD

**Issue by NtchPlayer** [jualoppaz/nuxt-youtube-subscribe-module#2]
Hi !
I discover your package today and it's a very good idea ! I have the exact same problem for my Nuxt application as you so thx you a lot to create this package :D

I just found a little error on your code for the gestion of the theme of the button (dark or white) in your code !
In your render fonction plugin.template.js you forget to add param theme in the option const. So the theme is not apply on the button even if we set the params theme. (See my screen I add the line).

I correct it for me but I think it's bette you make the correction directly here for everyone !

Thx again for your amazing package ! 👍

(Excuse me for my very bad English. French here 🇫🇷 ^^)
<img width="493" alt="Capture d’écran 2021-12-27 à 01 27 22" src="https://user-images.githubusercontent.com/64465776/147423718-1148e0cf-4ac8-4515-bff2-99f2192cdb5e.png">

**Comment by jualoppaz** [comment]
Hi, @NtchPlayer !

I have just fixed the error you mention.  You can use the dark theme now in the 0.1.2 version.

Thank you so much for reporting it!
